spring:
  application:
    name: rumoo-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080/auth}/realms/${KEYCLOAK_REALM:Rumoo}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true

server:
  error:
    include-message: always

logging:
  level:
    com.rumo: DEBUG
